### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by superzjn** [claytonsilva/aws-sso-cred-restore#11]
Hello,

I am getting the following error when running aws-sso-cred-restore. Any suggestions? Thanks a lot

> Traceback (most recent call last):
  File "/usr/local/bin/aws-sso-cred-restore", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/awsssocredrestore/__init__.py", line 188, in main
    process_profile(profile, args.export)
  File "/usr/local/lib/python3.9/site-packages/awsssocredrestore/__init__.py", line 164, in process_profile
    sso_access_token = retrieve_token(sso_start_url, sso_region, profile)
  File "/usr/local/lib/python3.9/site-packages/awsssocredrestore/__init__.py", line 119, in retrieve_token
    token = retrieve_token_from_file(cachefile, sso_start_url, sso_region)
  File "/usr/local/lib/python3.9/site-packages/awsssocredrestore/__init__.py", line 95, in retrieve_token_from_file
    blob = json.load(json_file)
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 3131: invalid start byte

**Comment by claytonsilva** [comment]
this is a problem with encode function when retrieve cache file:

https://stackoverflow.com/questions/38518023/unicodedecodeerror-utf8-codec-cant-decode-byte-0x80-in-position-3131-invali

**Comment by claytonsilva** [comment]
https://github.com/claytonsilva/aws-sso-cred-restore/blob/master/awsssocredrestore/__init__.py#L112-L122

**Comment by superzjn** [comment]
@claytonsilva Thank you so much! The issue was resolved by removing .DS_store file
